### ISSUE TITLE
Endline Census -- primary water source -- government provided community tap

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#144]
Hi @Archi11Gupta, flagging that there's 1 case so far in the endline census where someone reported using a "Government provided community tap (like Vasuhda)"

This just stands out to me because you would expect a community tap to also be used by other households. I wanted to flag in case this was something we could check with the team. This is lower priority now, but flagging it so we don't forget later.

**Comment by Archi11Gupta** [comment]
I think Jeremy there would be some cases for that because we also surveyed Bapuji nagar hamlet in Karlakana where the primary source of the water was swajaldhara taps which is a type of government household tap connection.  But it shouldn't be just one case because last time I checked there were a few responses like this and I also checked with the field team about the same @jlowe-git

**Comment by niharika-bhagavatula** [comment]
Closing this issue following the discussion that we might consider clubbing the responses into categories of "Using JJM tap water" and "using other sources" for analysis.
