### ISSUE TITLE
Baseline Data issues - 14th oct & 16th oct

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#65]
14th Oct - (Baseline HH case)
1) Village - Bada Alubadi
The HHID - 50601-104-026 was given for the HH survey and their primary drinking source was Handpump so the surveyor collected running water samples from Handpump for both the IDEXX water sample and running water testing

16th oct- (Baseline census)
1) In Tandipur, 30301-109-011 HH ID house has 2 kitchens which means 2 households. On the first day this household was found to be locked so were allotted the number 011 but the next day we found the respondents here so we found 2 families. 2 separate surveys were submitted, one with ID 30301-109-011 and the other, 30301-109-025.

2)  In Tandipur, 30301-119-023 HH ID house has 2 kitchens which means 2 households. On the first day this household was found to be locked so were allotted the number 023 but the next day we found the respondents here so we found 2 families. 2 separate surveys were submitted, one with ID 30301-119-023 and the other, 30301-119-025.

**Comment by jlowe-git** [comment]
Hi @Archi11Gupta, for the Bada Alubadi water testing, we should instruct the enumerator to not conduct water testing in this scenario. We should conduct water quality testing in the next HH in the list as a replacement. If households we visit say that they use a handpump for their primary source, we don't want to do water quality testing there, because we are mostly concerned with the tap connection

@avohra29 I think we should exclude these water quality test results in the survey for 50601104026 since it's not representing the tap connection quality

**Comment by Archi11Gupta** [comment]
Hey Jeremy,

But that is given to us in the randomized household list right. On that I
had called to check with Michelle about how did we get this, she said that
we including households even if tap isn't their primary source. So, earlier
I made the team skip that household with handpump but then after the call
with Michelle we did it.

If we are not randomising on JJM as the primary source then how can we
exclude such households. It would be great if you can explain this.

Thanks!

Regards,
Archi

**Comment by jlowe-git** [comment]
I think I am missing something, because our randomization does select for HHs who are using tap connections as their primary source. We don't want to select for HHs who do not say they use tap connections as their primary source.

@mich1995 can you confirm what the randomization code selects for now?

**Comment by Archi11Gupta** [comment]
Hey, Jeremy!
As far as I know, randomization also selects for households who report JJM
as their secondary source too. I think basic criteria is they should have
JJM connections.

Regarding this, I had a chat with Vaishnavi she said we are also selecting
households even if JJM isn't their primary source. She also mentioned that
if you go on field and find that for running water test water wasn't coming
through JJM tap you just select "running water not collected for that
household" instead of taking running water  from the non-JJM source
This is what we did on last 2 days too
Though I am yet to get a confirmation on if IDEXX sample is assigned to the
household where JJM water isn't the primary source so we won't be able to
collect JJM tap water. In that situation do we select a backup household
for water sample collection or not. But if we don't we will only have 3
samples from the village.

Though on Saturday I made the team use back up for IDEXX but it would be
great if you can confirm
@Jeremy Lowe ***@***.***>

Regards,
Archi

**Comment by jlowe-git** [comment]
Hey there, I think we had a miscommunication on our team originally and need to clarify things. We're still working on finalizing what the protocol should be and will follow up soon.

I'm thinking we will want to use a replacement HH though for the IDEXX sample and collect from their tap connection. We do not want to conduct IDEXX tests directly from handpumps or other alternative sources.
