### ISSUE TITLE
Water quality testing - Running water tests not done because JJM wasn't the primary source (Protocol discussion)

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#75]
DT- 21.10.2023
Follow-up Survey.
Vill- Bhujbal
Block- Kolnara
Gp- Kolnara
Household ID - 30501-117-021
This ID was originally assigned for IDEXX sample collection but here primary water source is Boring water and only FCT and TCT for stored water have been done here. For the IDEXX water sample, HHID- 30501- 106- 038 water sample collection has been done from Backup and both FCT and TCT tests for stored and running water have been done 

Date - 21st Oct
Village - Sanagortha 
10201-113-016 
Here only storage water FCT and TCT have been done because running water was a Non-JJM source here 

@avohra29 @jlowe-git
Please take a look at this

**Comment by jlowe-git** [comment]
For case 1 (30501-117-021), this makes sense to use the backup house. In this case, you also don't need to do chlorine testing at the household. We only want to do testing at HHs that use JJM water as their primary or secondary source.

For case 2 (10201-113-016) we also should just replace this HH since JJM isn't a primary or secondary source.
