### ISSUE TITLE
Classification of the water source - Neighbour's household taps 

### ISSUE THREAD

**Issue by Archi11Gupta** [DevInnovationLab/i-h2o-india#76]
Want a confirmation on the classification of  the water sources of households  who consume water from their neighbor's household taps (JJM) (@jlowe-git please confirm) 
**Current protocol**- The team marks it as their own individual household tap connections (But to confirm if the enumerators really did this, the way to check this would be by going through the comments of the survey. I suggest we see for the villages where JJM as a primary drinking source is low and see if enumerators have highlighted this issue in the comments and selected some other options instead of JJM tap because they thought it is of  their neighbors) 

It would also be great to compare answers for the same questions from census and household surveys to see differences in the answers and if they are different then we generate a new list of IDs that have such cases. We can do these along with the quality checks. Please send this list by today.

@avohra29 please send this list

**Comment by jlowe-git** [comment]
Hi @Archi11Gupta, I thought we had talked about this before, but yes they should keep labelling it as using the government provided household tap connection. It's often the case that these taps are only a meter away from one another, so that doesn't make a large difference in access.

 If it's the case where they're having to walk a farther distance (like 5 min) to a community tap connection, then we should mark it as a community tap connection

**Comment by Archi11Gupta** [comment]
This was resolved
