### ISSUE TITLE
Weekly Chlorine Monitoring Form -- Tandipur label incorrect, Dec 2nd, 2023

### ISSUE THREAD

**Issue by jlowe-git** [DevInnovationLab/i-h2o-india#94]
Hey there @Archi11Gupta,

I'm working through the data a bit more now and noticed that one date in the weekly chlorine monitoring form was wrong. It says that the weekly chlorine monitoring happened there on Dec 2, 2023, but the device was installed much later on Dec 23, 2023. I think someone may have selected the wrong village code for this survey, because the hamlet name is listed as Gopi Kankubadi.

Can you just confirm this submission on Dec 2nd was actually supposed to be for Gopi Kankubadi?

**Comment by Archi11Gupta** [comment]
Hi Jeremy, yes you are right the label is wrong and I had mentioned this in our slack group that Gopi Kankubadi wasn't present in the list then that's why they selected a different village so the correct village should be Gopi Kankubadi but then I had added Gopi Knakubadi in the lsit.  Please refer to this sheet- https://docs.google.com/spreadsheets/d/1CN8XRd2l6J07z18GdbWBZhbYuQrN--Wd2c7IpRWwKtY/edit#gid=0

Hey, Astha could you please correct this? Sorry for not getting back to you on this earlier

**Comment by jlowe-git** [comment]
Okay thanks. I was struggling to understand your previous message. Do we
have a way to correct this in surveycto or should Astha/I correct this in
data cleaning?

Thanks,
Jeremy

**Comment by Archi11Gupta** [comment]
This is already corrected in the survey cto form now. Now the change needs to be incorporated in data quality checks.

**Comment by jlowe-git** [comment]
Okay right, I think what I meant to ask is: Can we edit these submitted survey forms now to say Gopi Kankubadi? Or should Astha/I correct the data in R?

**Comment by Archi11Gupta** [comment]
That's done in form. I can make the change in the data as well.

Regards,
Archi

**Comment by niharika-bhagavatula** [comment]
No changes required given this observation is in the Chlorine monitoring dataset that was being used for tracking chlorine readings alone and we are currently using "Daily Chlorine Monitoring" dataset. - Marking as resolved
